### ISSUE TITLE
[SAM] What is the guidance to choose a proper graph_sampler?

### ISSUE THREAD

**Issue by ConnLiu** [FenTechSolutions/CausalDiscoveryToolbox#101]
@Diviyan-Kalainathan  
As you codes show, there are different graph_sampler like SimpleMatrixConnection\ MatrixSampler(Gumble)\MatrixSampler2\MatrixSampler3.
So I am wondering how to choose a proper one? And why you create various graph_sampler?

**Comment by Diviyan-Kalainathan** [comment]
Hello @ConnLiu,

These different graph samplers originate from how they are sampled (gumble softmax, etc...) ; usually, it is recommended to leave this parameter as default ; this parameter was used in development and cross-evaluated. This is kept for retro-compatibility, but we might retrain this parameter in the near future.

Hope this answers your question;
Best,
Diviyan

**Comment by ConnLiu** [comment]
Got it~
Thanks a lot!
By the way, are you planning to submit the SAM paper to a conference or journal? I think it would be nice to see this work published!

**Comment by Diviyan-Kalainathan** [comment]
Thanks for the kind words :) The paper is in the process of submission for JMLR!

Best,
Diviyan
