### ISSUE TITLE
[BUG] PC algorithm, R Packages (k)pcalg/RCIT is not available

### ISSUE THREAD

**Issue by AlexanderCui001228** [FenTechSolutions/CausalDiscoveryToolbox#104]
The flowing image has a code snippet with the error:

![image](https://user-images.githubusercontent.com/34061099/119964523-e1aebb80-bfdb-11eb-94ac-1c15b20944f3.jpeg)

I installed RCIT, pcalg, kpcalg, MASS, momentchi2, and ran the following code (from readme):

library(devtools)
install_github("erictrobl/RCIT")
library(RCIT)
RCIT(rnorm(1000),rnorm(1000),rnorm(1000))
RCoT(rnorm(1000),rnorm(1000),rnorm(1000))
RCoT(rnorm(1000),rnorm(1000),matrix(rnorm(2000),1000,2)

My R packages are:

![image](https://user-images.githubusercontent.com/34061099/119964600-f4c18b80-bfdb-11eb-992a-676975d2f330.jpeg)

System: 64bit windows10
GPU: 0
Python: 3.8.8
R: 3.6.3
RTools:3.5

What might be the problem here?

Thanks!

**Comment by Diviyan-Kalainathan** [comment]
Hello, 
It is strange, maybe `cdt` is looking at the wrong R executable. Could you execute : 
```python
import cdt
print(cdt.utils.Rpackages)
```
It might take some time, but it is testing the availability of all packages

**Comment by AlexanderCui001228** [comment]
> Hello,
> It is strange, maybe `cdt` is looking at the wrong R executable. Could you execute :
> 
> ```python
> import cdt
> print(cdt.utils.R.Rpackages)
> ```
> 
> It might take some time, but it is testing the availability of all packages|
> 
> Best,
> Diviyan

Hi,

It says "module 'cdt.utils.R' has no attribute 'Rpackages'

**Comment by Diviyan-Kalainathan** [comment]
Whoops, small typo, it's a capital P: 
```python
import cdt
print(cdt.utils.R.RPackages)
```

**Comment by AlexanderCui001228** [comment]
problem solved. I didn't install pcalg and kpcalg properly with BiocManager

**Comment by Diviyan-Kalainathan** [comment]
Great, I'll close the issue!
