### ISSUE TITLE
Blacklist support?

### ISSUE THREAD

**Issue by agentzel** [FenTechSolutions/CausalDiscoveryToolbox#112]
Do the packages that wrap bnlearn support blacklists?  While I can't find anything in the documentation about it, when I check the code for the BNlearnAlgorithm class, there are multiple mentions to a 'blacklist.csv' file, as well as a blacklist argument in _run_bnlearn.  However, I can't find any way to specify a blacklist when calling any bnlearn methods.  Is this a currently supported feature?

**Comment by Diviyan-Kalainathan** [comment]
Hello!
The algorithms do support the blacklist feature, but the whitelist feature is not supported yet ( Soon I hope). To provide a blacklist, just provide a nx.Graph( ) (undirected graph) with the blacklisted edges not in the graph, in the predict `graph=` argument

Hope this helps, 
DIviyan

**Comment by agentzel** [comment]
Great, thanks for the information! Since you have to provide the blacklist
as an undirected graph, does that mean that it doesn't currently support
blacklisting only a single direction? For example, if I know that A comes
before B, is there anyway to encode that, or blacklist just the B -> A
direction?

Thanks,
Amanda

**Comment by Diviyan-Kalainathan** [comment]
Hello,
After a quick check, it is better to use directly the `_run_bnlearn()` function (defined for all bnlearn algorithms : 


You can obtain the networkx.DiGraph 's blacklist with : 
```python
        blacklist = DataFrame(list(nx.edges(nx.DiGraph(DataFrame(-nx.adj_matrix(graph2, weight=None).todense() + 1,
                                                                 columns=list(graph2.nodes()),
                                                                 index=list(graph2.nodes()))))), columns=["from", "to"])

```

Actually, the digraph is managed strangely (a mix of whitelist and blacklist)

Hope this helps,
Diviyan
