### ISSUE TITLE
[BUG] Reference missing，a typo in paper

### ISSUE THREAD

**Issue by JiaxiangBU** [FenTechSolutions/CausalDiscoveryToolbox#121]
> Other approaches leverage the celebrated Generative Adversarial Network setting ?, such as CGNN or SAM (Goudet et al., 2017; Kalainathan et al., 2018). Graph setting methods output either a directed acyclic graph or a partially directed acyclic graph.

Here "?" imply a missing citation？

**Comment by Diviyan-Kalainathan** [comment]
Thanks for noticing, yes it's missing the GAN reference
