### ISSUE TITLE
Problems installing  R packages

### ISSUE THREAD

**Issue by Angela446-lgtm** [FenTechSolutions/CausalDiscoveryToolbox#127]
Does anybody know how to install the CAM package in R? - I found some difficulties trying to install it.

**Comment by shahdhardn** [comment]
Did you manage to solve this issue? If yes, please assist. Thanks.

**Comment by Diviyan-Kalainathan** [comment]
Hello,
The CAM package is a bit tricky to install (mix of Bioconductor version that should be correct + other packages)
Please use the docker image otherwise.

Best,
Diviyan

**Comment by Angela446-lgtm** [comment]
Hi, 
From http://cran.nexr.com/web/packages/CAM/index.html, I downloaded the CAM_1.0.tar.gz and imported it to R. 
it worked for me. 

Best, 
Angela

**Comment by MAX00008888** [comment]
> Hi, From http://cran.nexr.com/web/packages/CAM/index.html, I downloaded the CAM_1.0.tar.gz and imported it to R. it worked for me.
> 
> Best, Angela

hello, I want to ask how to imported CAM into R @Angela446-lgtm

**Comment by Diviyan-Kalainathan** [comment]
Hello, I updated the docker installation scripts for debian and ubuntu distributions, for R 4.2.1, please check here, it might give you commands to execute on your device : 

Debian :  [https://github.com/FenTechSolutions/base-docker-images/blob/main/cdt-env.dockerfile](https://github.com/FenTechSolutions/base-docker-images/blob/main/cdt-env.dockerfile)
Ubuntu : [https://github.com/FenTechSolutions/base-docker-images/blob/main/nv-cdt-env.dockerfile](https://github.com/FenTechSolutions/base-docker-images/blob/main/nv-cdt-env.dockerfile
)

This executes without any issues on CircleCI ! 

Hope this helps, 
Best regards, 
Diviyan

**Comment by Diviyan-Kalainathan** [comment]
I will close this issue, please open a new one @MAX00008888  if you still encounter some issues
