### ISSUE TITLE
R packages not installed on mac via conda

### ISSUE THREAD

**Issue by vdemchenko3** [FenTechSolutions/CausalDiscoveryToolbox#131]
I added cdt to my yaml file, however the relevant R packages (namely BiocManager and all the causal discovery algorithms) are not added.  I'm having similar issues to #123 and there's some discrepancy between the dependency builds.  

Can you provide the steps to get all the necessary R packages for Mac rather than Ubuntu?

**Comment by Diviyan-Kalainathan** [comment]
Hello, the install should be similar...  check out the new installation section ([here](https://github.com/FenTechSolutions/CausalDiscoveryToolbox#additional--r-and-r-libraries)), you could try the commands `install.packages("https://cran.r-project.org/src/contrib/Archive/link_to_the_package.tar.gz", repos=NULL, type="source")`

Unfortunately, I don't have a Mac for comparison/dev/testing... so i suggest trying the abovementioned methods, or fall back on docker images

Best,
Diviyan
