### ISSUE TITLE
Something is wrong with PC algorithm in CausalDiscoveryToolbox.

### ISSUE THREAD

**Issue by williamty** [FenTechSolutions/CausalDiscoveryToolbox#136]
I used two packages to calculate DAG for the same dataset. But I got two different DAG. Another is using Tetrad. The two DAG are very different, and CDT's is definitely wrong!

**Comment by Diviyan-Kalainathan** [comment]
Hello,
We are actually using PC directly from the pcalg package, we only put a python wrapper around it.
Can you try running directly pcalg in R and compare its results with Tetrad? 
That would be really helpful, thanks a lot

**Comment by williamty** [comment]
Yes, that's what I'm going to do next. I'll report the result here later.

**Comment by williamty** [comment]
I think I know why. The dataset I used is real world data, ,so it's mixed. But I didn't deal with the mixed data before running the PC algorithm in CDT. Meanwhile, Tetrad dealt with the mixed data problem automatically.

**Comment by Diviyan-Kalainathan** [comment]
Thanks for the info ! Do you know how Tetrad manages this ? 

Best,
Diviyan

**Comment by williamty** [comment]
> 

It separates mixed data by pre-define the discrete data dimensions. Then it used Conditional Gaussian or Degenerated Gaussian algorithm to deal with relationships between continuous and discrete nodes.
