### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by uzumaki-sina** [FenTechSolutions/CausalDiscoveryToolbox#152]
I need to create connectivity matrix from pc algorithm but i dont know how to work the output format of the toolbox.
any help or tips?

**Comment by diviyank** [comment]
Hello ! 
It's a networkx Graph. 
Check nx.adjacency_matrix(output).to_dense()

More details here : https://networkx.org/documentation/stable/reference/generated/networkx.linalg.graphmatrix.adjacency_matrix.html#adjacency-matrix

Hope this helps
