### ISSUE TITLE
problem about the SAM model

### ISSUE THREAD

**Issue by Wangt-CN** [FenTechSolutions/CausalDiscoveryToolbox#61]
Hi, thanks for your great work, I have tried the SAM model on a 90 variables graph estimation.
However, after an hour, I found the loss become to nan (It's NOT always nan, sometimes seemed regularly)

Is that no problem? and need I change the lr or any parameters? (I just use the default parameters)

commond:
obj = SAM(gpus=3, njobs=6,nruns=16,batchsize=1024)                                                                             output = obj.predict(data)

output:
397/11000 [2:52:25<76:44:58, 26.06s/it, disc=nan, gen=nan, regul_loss=nan, tot=nan]
402/11000 [2:52:16<75:41:45, 25.71s/it, disc=6.07, gen=-0.992, regul_loss=0.49, tot=-78.9]

**Comment by ritik99** [comment]
Hello @Wangt-CN ,

Would it be possible for you to share the dataset you run the model on as well?

Thanks.

**Comment by Diviyan-Kalainathan** [comment]
Hi @Wangt-CN, 
Try setting the DAG constraint to 0 to see if the training stabilizes ; We noticed that the No-Tears might bring some instability in the loss. 
Best, 
Diviyan

**Comment by Diviyan-Kalainathan** [comment]
The datasets used in the paper are available in the `cdt.data.load_dataset` function, please check https://fentechsolutions.github.io/CausalDiscoveryToolbox/html/data.html#cdt.data.load_dataset

I will close this issue for inactivity, don't hesitate to reopen it if the issue persists or if you have more questions.

Best,
Diviyan
