### ISSUE TITLE
SAM doesn't return right DAG

### ISSUE THREAD

**Issue by arthurshatver** [FenTechSolutions/CausalDiscoveryToolbox#65]
I just run example in documentation https://fentechsolutions.github.io/CausalDiscoveryToolbox/html/causality.html#sam .
I got complete graph, where every node is connected with all others nodes.
is it something i don't do right.

![1](https://user-images.githubusercontent.com/60813199/81666468-201a1c80-9453-11ea-85be-d7fe7fcb178c.PNG)

![2](https://user-images.githubusercontent.com/60813199/81666488-27d9c100-9453-11ea-9579-03897c713f65.PNG)

**Comment by Diviyan-Kalainathan** [comment]
Hello Arthur, 

Actually the hyperparameters (mostly lambda1 and lambda2) have to be a little tuned depending on the size of the graph. We thought of having it automatically set depending on the size, but finally chose of having the default fixed.
Could you try with : `lambda1 = .1`, `lambda2=1e-04`, `dagpenalization_increase=0.01` ? 

Best, 
Diviyan

**Comment by arthurshatver** [comment]
Hello Diviyan,

I did as you said, but nothing was changed 
![Capture](https://user-images.githubusercontent.com/60813199/81845528-bb99b300-9561-11ea-8574-30d004c2bbc3.PNG)

**Comment by arthurshatver** [comment]
> Hello Arthur,
> 
> Actually the hyperparameters (mostly lambda1 and lambda2) have to be a little tuned depending on the size of the graph. We thought of having it automatically set depending on the size, but finally chose of having the default fixed.
> Could you try with : `lambda1 = .1` and `lambda2=1e-04`?
> 
> This unittest was to show how the SAM works, I guess I should update it with the good parameters.
> 
> Best,
> Diviyan

Hello Diviyan,

I did as you said, but nothing was changed
![Capture](https://user-images.githubusercontent.com/60813199/81845967-6ad68a00-9562-11ea-83e8-cd07db821f1b.PNG)

**Comment by Diviyan-Kalainathan** [comment]
Hello again,
This is strange ; i'll look into it. If you have time; can you thest the implementation here: https://github.com/Diviyan-Kalainathan/SAM ?

**Comment by arthurshatver** [comment]
> Hello again,
> This is strange ; i'll look into it. If you have time, could you test with the implementation here: https://github.com/Diviyan-Kalainathan/SAM

**Comment by arthurshatver** [comment]
> Hello again,
> This is strange ; i'll look into it. If you have time, could you test with the implementation here: https://github.com/Diviyan-Kalainathan/SAM ?

I'm sorry,but again the same problem. You can close this issue. I will try other motheds.
Thank you for helping.

**Comment by Diviyan-Kalainathan** [comment]
Oh my I've just noticed your problem ! 

The fact is that SAM returns a confidence for each edge of the graph ( even fif it's close to 0). 
You would be able to see it with the adjacency matrix (`networkx.adjacency_matrix(output).todense()` i think). Therefore, it plots each edge as it is present in the graph (even if the associated weight is low.)

You must first proceed to threshold the confidence level of the graph before trying to plot it.
From experience, thresholding to .6 or .7 leads to obtaining the best results.

Best,
Diviyan

**Comment by Diviyan-Kalainathan** [comment]
I will close this issue for inactivity; as I consider it as solved.

**Comment by ConnLiu** [comment]
> Oh my I've just noticed your problem !
> 
> The fact is that SAM returns a confidence score for each edge of the graph ( even if it's close to 0).
> You would be able to see it with the adjacency matrix (`networkx.adjacency_matrix(output).todense()` i think). Therefore, it plots each edge as it is present in the graph (even if the associated weight is low.)
> 
> You must first proceed to threshold the confidence level of the graph before trying to plot it.
> From experience, thresholding to .6 or .7 leads to obtaining the best results.
> 
> Best,
> Diviyan

Hi,
Your algorithm is really awesome, and I am wondering about how you transform the output of SAM( the confidence score matrix) to a causal graph which is DAG. 
I have tried thresholding to .6 or .7, but it returns a bad result. As the picture shows below, there are only several edges but a loop.
<img width="160" alt="image" src="https://user-images.githubusercontent.com/15926859/113236427-65e40b80-92d7-11eb-86c9-cbad7aea095d.png">
