### ISSUE TITLE
No module named 'sklearn.externals.joblib'

### ISSUE THREAD

**Issue by hanan-vian** [FenTechSolutions/CausalDiscoveryToolbox#69]
Import causes an error:
```
from cdt.independence.graph import DecisionTreeRegression
```
> ModuleNotFoundError: No module named 'sklearn.externals.joblib'

* Versions
    - cdt==0.5.18
    - Python 3.8.3
    - torch==1.5.1
    - NO GPU

* Traceback

> No GPU automatically detected. Setting SETTINGS.GPU to 0, and SETTINGS.NJOBS to cpu_count.
> ---------------------------------------------------------------------------
> ModuleNotFoundError                       Traceback (most recent call last)
> <ipython-input-2-a9aaa1dea19b> in <module>
> ----> 1 from cdt.independence.graph import DecisionTreeRegression
>       2 from sklearn.datasets import load_boston
>       3 boston = load_boston()
>       4 df_features = pd.DataFrame(boston['data'])
>       5 df_target = pd.DataFrame(boston['target'])
> 
> ~/opt/anaconda3/envs/causal_bi/lib/python3.8/site-packages/cdt/__init__.py in <module>
>      27 
>      28 import cdt.causality
> ---> 29 import cdt.independence
>      30 import cdt.data
>      31 import cdt.metrics
> 
> ~/opt/anaconda3/envs/causal_bi/lib/python3.8/site-packages/cdt/independence/__init__.py in <module>
>      23 """
>      24 from .stats import __init__ as stats
> ---> 25 from .graph import __init__ as skeleton
> 
> ~/opt/anaconda3/envs/causal_bi/lib/python3.8/site-packages/cdt/independence/graph/__init__.py in <module>
>      24 from .Lasso import (Glasso, HSICLasso)
>      25 from .FSGNN import FSGNN
> ---> 26 from .FSRegression import (RFECVLinearSVR, LinearSVRL2, RRelief,
>      27                            DecisionTreeRegression, ARD)
> 
> ~/opt/anaconda3/envs/causal_bi/lib/python3.8/site-packages/cdt/independence/graph/FSRegression.py in <module>
>      31 from sklearn.svm import SVR, LinearSVR
>      32 from sklearn.tree import DecisionTreeRegressor
> ---> 33 from skrebate import ReliefF
>      34 import numpy as np
>      35 from sklearn.linear_model import ARDRegression as ard
> 
> ~/opt/anaconda3/envs/causal_bi/lib/python3.8/site-packages/skrebate/__init__.py in <module>
>      26 
>      27 from ._version import __version__
> ---> 28 from .relieff import ReliefF
>      29 from .surf import SURF
>      30 from .surfstar import SURFstar
> 
> ~/opt/anaconda3/envs/causal_bi/lib/python3.8/site-packages/skrebate/relieff.py in <module>
>      31 import sys
>      32 from sklearn.base import BaseEstimator
> ---> 33 from sklearn.externals.joblib import Parallel, delayed
>      34 from .scoring_utils import get_row_missing, ReliefF_compute_scores
>      35 
> 
> ModuleNotFoundError: No module named 'sklearn.externals.joblib'
>

**Comment by Diviyan-Kalainathan** [comment]
Hello,
Thanks for the feedback
Ok it comes from an API change from sklearn ; for a hotfix downgrade sklearn, I'm on it otherwise 
Best,
Diviyan

**Comment by Diviyan-Kalainathan** [comment]
Fixed in bef67c2, I will release the next version soon (next week) ! Please reopen if the issue still persists.

**Comment by sdhaus** [comment]
When will this version be released?

**Comment by Diviyan-Kalainathan** [comment]
Sorry for the delay, I wished to fix a maximum of bugs before the new release: in the meantime you can update your package from git : 

```sh
pip uninstall cdt
pip install pip install git+https://github.com/FenTechSolutions/CausalDiscoveryToolbox.git@ac6267a1927bead1d9c3e08ec09e3a2e84c575a5
```
Best,
Diviyan

**Comment by Diviyan-Kalainathan** [comment]
The cdt 0.5.21 has been released on Pypi!
