### ISSUE TITLE
[BUG]  Issue when i use functions that use R functions

### ISSUE THREAD

**Issue by Margaux-Chevallier** [FenTechSolutions/CausalDiscoveryToolbox#70]
Hello !

I am working on a Causal Learning projectCausal Learning project, I would like to use the CausalDiscoveryToolbox (cdt) package to find the causal graph that fits my problem.

I'm working on Windows on a Python(version: 3.7.6) anaconda notebook. The package installs correctly (version : 0.5.18). But when I use functions in the package that use R functions, I get an error (e.g. ImportError: R Package pcalg is not available). However, I have installed all the necessary R packages on R. Rscipt is well intalls and i can execute some scripts with. So I tried to change the path of the following variable  cdt.SETTINGS.rpath by "C:\Program Files\R\R-3.6.3\bin\Rscript" but it doesn't work. 

Thank you in advance for your help!

**Comment by nishtha82** [comment]
Even I am facing the same issue. Hoping for help on this! Thanks!

**Comment by Diviyan-Kalainathan** [comment]
I'm not really using Windows to work on CDT, so this issue may take a bit more time to fix ; what happens if you run this small code snippet ? (Run the python code)

```R
#testlib.R
result = library("pcalg")
```

```python
#test.py
import subprocess
output = subprocess.call("{} --vanilla {}".format("C:\Program Files\R\R-3.6.3\bin\Rscript", "testlib.R"), shell=True,
                                     stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
print(output)
```

A quick and easy solution would be to use the Docker images to run your scripts, in the meantime. 

I'll try took look into it  ! 
Best,
Diviyan

**Comment by nishtha82** [comment]
Hello, thanks for the response:)
The testlib.R works fine
the test.py gives the output as 1.
Thanks for the advice, I will try to use with a docker image meanwhile!

**Comment by Diviyan-Kalainathan** [comment]
Hello again,

`1` means that the script has errored (0 means no error) ; is your path to the Rscript executable `C:\Program Files\R\R-3.6.3\bin\Rscript` ? If not, can you run it with the correct path ? 

Best regards,

**Comment by nishtha82** [comment]
Hello
My path is `C:\Program Files\R\R-4.0.2\bin\Rscript` 
This gives error again.
Is it issue with the R version?

**Comment by nishtha82** [comment]
Also very kind of you to take time to look into this :)

**Comment by Diviyan-Kalainathan** [comment]
Hello again, 

No problem :)

I'm trying on a windows platform and encountered small bugs myself, but solved them ;  can you try : 

```python
#test.py
import subprocess
output = subprocess.call(r"C:\Program Files\R\R-4.0.2\bin\Rscript --vanilla testlib.R", shell=True)
print(output)
```

This may sound silly, but can you import "pcalg" correctly from an R console ? 

Best,
Diviyan

**Comment by nishtha82** [comment]
Hello
When i ran it -
```
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
1

Process finished with exit code 0
```
Yeah I am able to import pcalg from R console without an issue

**Comment by Margaux-Chevallier** [comment]
Hello, 

Thank you for your response! 

I can import correctly "pcalg" from R console

I tried the code you give and I get 1.

**Comment by Margaux-Chevallier** [comment]
I tried the following code and I get 0.

import subprocess
command = "C:/Program Files/R/R-3.6.3/bin/Rscript"
arg = '--vanilla'
path2script = "C:/Users/UT/Documents/margaux/testlib.R"
output = subprocess.call([command, arg, path2script], shell=True)
print (output)

**Comment by nishtha82** [comment]
Hello

This works for my configuration too!

**Comment by Diviyan-Kalainathan** [comment]
Thank you for your feedback ! The issue comes from the path management that differs from Linux and Windows ; I'll try to patch this asap

**Comment by nishtha82** [comment]
Thanks a lot:)

**Comment by Diviyan-Kalainathan** [comment]
It should be fixed in the `dev` branch, can you check if everything works on your side ?

**Comment by nishtha82** [comment]
Hello
I am running into this issue 

```
Connected to pydev debugger (build 201.7846.77)
Detecting 1 CUDA device(s).
Traceback (most recent call last):
  File "C:\PML Code\Causal discovery\CausalDiscoveryToolbox\cdt\utils\R.py", line 207, in launch_R_script
    raise e
  File "C:\PML Code\Causal discovery\CausalDiscoveryToolbox\cdt\utils\R.py", line 192, in launch_R_script
    output = subprocess.call([rpath, "--vanilla", scriptpath])
  File "C:\Users\DELL\Anaconda3\lib\subprocess.py", line 339, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\DELL\Anaconda3\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Users\DELL\Anaconda3\lib\subprocess.py", line 1148, in _execute_child
    args = list2cmdline(args)
  File "C:\Users\DELL\Anaconda3\lib\subprocess.py", line 555, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: argument of type 'WindowsPath' is not iterable
```

when I was running 

```
import networkx as nx
from cdt.causality.graph import PC
from cdt.data import load_dataset
data, graph = load_dataset("sachs")
obj = PC()
```

**Comment by Diviyan-Kalainathan** [comment]
Can you try setting manually the rpath before calling PC? 

```
import cdt
import networkx as nx
from cdt.causality.graph import PC
from cdt.data import load_dataset
data, graph = load_dataset("sachs")
cdt.SETTINGS.rpath= r'C:\Program Files\R\R-4.0.2\bin\Rscript'
obj = PC()
```
It seems to be working that way on my windows machine...

**Comment by nishtha82** [comment]
I tried manually setting the path. Same error coming up

```
Traceback (most recent call last):
  File "C:/PML Code/Causal discovery/CausalDiscoveryToolbox/trial.py", line 7, in <module>
    obj = PC()
  File "C:\PML Code\Causal discovery\CausalDiscoveryToolbox\cdt\causality\graph\PC.py", line 175, in __init__
    if not (RPackages.pcalg and RPackages.kpcalg and RPackages.RCIT):
  File "C:\PML Code\Causal discovery\CausalDiscoveryToolbox\cdt\utils\R.py", line 132, in __getattribute__
    availability = self.check_R_package(name)
  File "C:\PML Code\Causal discovery\CausalDiscoveryToolbox\cdt\utils\R.py", line 147, in check_R_package
    {"{package}": package}, verbose=True))
  File "C:\PML Code\Causal discovery\CausalDiscoveryToolbox\cdt\utils\R.py", line 207, in launch_R_script
    raise e
  File "C:\PML Code\Causal discovery\CausalDiscoveryToolbox\cdt\utils\R.py", line 192, in launch_R_script
    output = subprocess.call([rpath, "--vanilla", scriptpath])
  File "C:\Users\DELL\Anaconda3\lib\subprocess.py", line 339, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\DELL\Anaconda3\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Users\DELL\Anaconda3\lib\subprocess.py", line 1148, in _execute_child
    args = list2cmdline(args)
  File "C:\Users\DELL\Anaconda3\lib\subprocess.py", line 555, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: argument of type 'WindowsPath' is not iterable

Process finished with exit code 1

```

**Comment by Diviyan-Kalainathan** [comment]
I converted the paths to `str`, can you pull `dev` and try again ? 
I think that this issue is linked to package versions : your version of subprocess doesn't seem to support pathlib.Path objects

**Comment by nishtha82** [comment]
Hello
Awesome, thanks a lot, that works!
But running  `output = obj.predict(data)` throws error
```

Connected to pydev debugger (build 201.7846.77)
Detecting 1 CUDA device(s).
Loading required package: momentchi2
Loading required package: MASS
Error: '\d' is an unrecognized escape in character string starting "'C:\\Users\\DELL\\AppData\\Local\\Temp\\cdt_pc_4a26313d-831b-402f-a21d-e0f5b3ac137c\d"
Execution halted
Traceback (most recent call last):
  File "C:\PML Code\Causal discovery\CausalDiscoveryToolbox\cdt\causality\graph\PC.py", line 286, in _run_pc
    raise e
  File "C:\PML Code\Causal discovery\CausalDiscoveryToolbox\cdt\causality\graph\PC.py", line 282, in _run_pc
    self.arguments, output_function=retrieve_result, verbose=verbose)
  File "C:\PML Code\Causal discovery\CausalDiscoveryToolbox\cdt\utils\R.py", line 196, in launch_R_script
    raise e
  File "C:\PML Code\Causal discovery\CausalDiscoveryToolbox\cdt\utils\R.py", line 190, in launch_R_script
    output = output_function()
  File "C:\PML Code\Causal discovery\CausalDiscoveryToolbox\cdt\causality\graph\PC.py", line 265, in retrieve_result
    return read_csv(Path('{}/result.csv'.format(run_dir)), delimiter=',').values
  File "C:\Users\DELL\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 676, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\DELL\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 448, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "C:\Users\DELL\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 880, in __init__
    self._make_engine(self.engine)
  File "C:\Users\DELL\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 1114, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "C:\Users\DELL\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 1891, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas\_libs\parsers.pyx", line 374, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas\_libs\parsers.pyx", line 674, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] File C:\Users\DELL\AppData\Local\Temp\cdt_pc_4a26313d-831b-402f-a21d-e0f5b3ac137c\result.csv does not exist: 'C:\\Users\\DELL\\AppData\\Local\\Temp\\cdt_pc_4a26313d-831b-402f-a21d-e0f5b3ac137c\\result.csv'

Process finished with exit code 1
```

**Comment by Margaux-Chevallier** [comment]
Hello !

I tried the following code but I still have the error : ImportError: R Package (k)pcalg/RCIT is not available. RCIT has to be installed from https://github.com/Diviyan-Kalainathan/RCIT.

import cdt
import networkx as nx
from cdt.causality.graph import PC
from cdt.data import load_dataset
data, graph = load_dataset("sachs")
cdt.SETTINGS.rpath= r"C:/Program Files/R/R-3.6.3/bin/Rscript"
obj = PC()

I used pip install cdt --upgrade to have the changement of the code that you made but I think it doesn't work.

**Comment by nishtha82** [comment]
Have you installed RCIT from https://github.com/Diviyan-Kalainathan/RCIT.?? @Margaux-Chevallier

**Comment by Diviyan-Kalainathan** [comment]
@Margaux-Chevallier You need to install those two packages : 
from R:
```R
install.packages('kpcalg')
install.packages('devtools')
library('devtools')
install_github("Diviyan-Kalainathan/RCIT")
```

@nishtha82 Strange, I'll look into it

**Comment by nishtha82** [comment]
Hello again,
Awesome, looking forward to that!
Thanks much for all the help so far:)

**Comment by Margaux-Chevallier** [comment]
I checked, the package RCIT and kpcalg are well install on R.

**Comment by Diviyan-Kalainathan** [comment]
@Margaux-Chevallier Using `pip install cdt --upgrade` doen't work, only master is pushed to pypi.

One thing you could do is : 
```sh
pip uninstall cdt 
pip install git+https://github.com/FenTechSolutions/CausalDiscoveryToolbox.git@1dcd97a34e73cfaf7e6820ab06760f7d8dded4b2
```

`1dcd97a34e73cfaf7e6820ab06760f7d8dded4b2` refers to the latest commit as of now.

**Comment by Diviyan-Kalainathan** [comment]
Could you try again ?  

```sh
pip install git+https://github.com/FenTechSolutions/CausalDiscoveryToolbox.git@1e553f49b4adb7ccc19f7d8fc473ec875b554ab4
```

**Comment by Margaux-Chevallier** [comment]
Thanks !

I run this :
pip uninstall cdt --yes
pip install git+https://github.com/FenTechSolutions/CausalDiscoveryToolbox.git@1e553f49b4adb7ccc19f7d8fc473ec875b554ab4
import cdt
import networkx as nx
from cdt.causality.graph import PC
from cdt.data import load_dataset
data, graph = load_dataset("sachs")
cdt.SETTINGS.rpath= r'C:/Program Files/R/R-3.6.3/bin/Rscript'
obj = PC()

And I still have the same issue.

**Comment by Margaux-Chevallier** [comment]
Sorry, I didn't restart the kernel...

It's working now !!! Thanks a lot for your help and your reactivity !

**Comment by nishtha82** [comment]
@Diviyan-Kalainathan  I found this issue https://github.com/FenTechSolutions/CausalDiscoveryToolbox/issues/50 which is similar to mine, but couldn't understand the workaround suggested?

**Comment by Margaux-Chevallier** [comment]
I thik I have a similar issue when I use the CAM method.

import cdt
import networkx as nx
from cdt.causality.graph import CAM
from cdt.data import load_dataset
data, graph = load_dataset("sachs")
cdt.SETTINGS.rpath= r'C:/Program Files/R/R-3.6.3/bin/Rscript'
obj = CAM()
output = obj.predict(data)

Running the last line give the following error :
FileNotFoundError: [Errno 2] File C:\Users\UT\AppData\Local\Temp\cdt_cam_67b55cc5-05a5-4373-8650-44c9f2e4206b\result.csv does not exist: 'C:\\Users\\UT\\AppData\\Local\\Temp\\cdt_cam_67b55cc5-05a5-4373-8650-44c9f2e4206b\\result.csv'

The detailed error is : 
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-5-790d45961d7d> in <module>
      6 cdt.SETTINGS.rpath= r'C:/Program Files/R/R-3.6.3/bin/Rscript'
      7 obj = CAM()
----> 8 output = obj.predict(data)

~\anaconda3\lib\site-packages\cdt\causality\graph\model.py in predict(self, df_data, graph, **kwargs)
     61         """
     62         if graph is None:
---> 63             return self.create_graph_from_data(df_data, **kwargs)
     64         elif isinstance(graph, nx.DiGraph):
     65             return self.orient_directed_graph(df_data, graph, **kwargs)

~\anaconda3\lib\site-packages\cdt\causality\graph\CAM.py in create_graph_from_data(self, data, **kwargs)
    179         self.arguments['{NJOBS}'] = str(self.njobs)
    180         self.arguments['{VERBOSE}'] = str(self.verbose).upper()
--> 181         results = self._run_cam(data, verbose=self.verbose)
    182 
    183         return nx.relabel_nodes(nx.DiGraph(results),

~\anaconda3\lib\site-packages\cdt\causality\graph\CAM.py in _run_cam(self, data, fixedGaps, verbose)
    201         except Exception as e:
    202             rmtree(run_dir)
--> 203             raise e
    204         except KeyboardInterrupt:
    205             rmtree(run_dir)

~\anaconda3\lib\site-packages\cdt\causality\graph\CAM.py in _run_cam(self, data, fixedGaps, verbose)
    197             data.to_csv(Path('{}/data.csv'.format(run_dir)), header=False, index=False)
    198             cam_result = launch_R_script(Path("{}/R_templates/cam.R".format(os.path.dirname(os.path.realpath(__file__)))),
--> 199                                          self.arguments, output_function=retrieve_result, verbose=verbose)
    200         # Cleanup
    201         except Exception as e:

~\anaconda3\lib\site-packages\cdt\utils\R.py in launch_R_script(template, arguments, output_function, verbose, debug)
    207         if not debug:
    208             rmtree(base_dir)
--> 209         raise e
    210     except KeyboardInterrupt:
    211         if not debug:

~\anaconda3\lib\site-packages\cdt\utils\R.py in launch_R_script(template, arguments, output_function, verbose, debug)
    201                                            stderr=subprocess.DEVNULL)
    202             process.wait()
--> 203             output = output_function()
    204 
    205     # Cleaning up

~\anaconda3\lib\site-packages\cdt\causality\graph\CAM.py in retrieve_result()
    192 
    193         def retrieve_result():
--> 194             return read_csv(Path('{}/result.csv'.format(run_dir)), delimiter=',').values
    195 
    196         try:

~\anaconda3\lib\site-packages\pandas\io\parsers.py in parser_f(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, skipfooter, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, cache_dates, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, doublequote, escapechar, comment, encoding, dialect, error_bad_lines, warn_bad_lines, delim_whitespace, low_memory, memory_map, float_precision)
    674         )
    675 
--> 676         return _read(filepath_or_buffer, kwds)
    677 
    678     parser_f.__name__ = name

~\anaconda3\lib\site-packages\pandas\io\parsers.py in _read(filepath_or_buffer, kwds)
    446 
    447     # Create the parser.
--> 448     parser = TextFileReader(fp_or_buf, **kwds)
    449 
    450     if chunksize or iterator:

~\anaconda3\lib\site-packages\pandas\io\parsers.py in __init__(self, f, engine, **kwds)
    878             self.options["has_index_names"] = kwds["has_index_names"]
    879 
--> 880         self._make_engine(self.engine)
    881 
    882     def close(self):

~\anaconda3\lib\site-packages\pandas\io\parsers.py in _make_engine(self, engine)
   1112     def _make_engine(self, engine="c"):
   1113         if engine == "c":
-> 1114             self._engine = CParserWrapper(self.f, **self.options)
   1115         else:
   1116             if engine == "python":

~\anaconda3\lib\site-packages\pandas\io\parsers.py in __init__(self, src, **kwds)
   1889         kwds["usecols"] = self.usecols
   1890 
-> 1891         self._reader = parsers.TextReader(src, **kwds)
   1892         self.unnamed_cols = self._reader.unnamed_cols
   1893 

pandas\_libs\parsers.pyx in pandas._libs.parsers.TextReader.__cinit__()

pandas\_libs\parsers.pyx in pandas._libs.parsers.TextReader._setup_parser_source()

FileNotFoundError: [Errno 2] File C:\Users\UT\AppData\Local\Temp\cdt_cam_67b55cc5-05a5-4373-8650-44c9f2e4206b\result.csv does not exist: 'C:\\Users\\UT\\AppData\\Local\\Temp\\cdt_cam_67b55cc5-05a5-4373-8650-44c9f2e4206b\\result.csv'

**Comment by Diviyan-Kalainathan** [comment]
Hello,
@Margaux-Chevallier CAM should run correctly now, please take the lastest commit on dev
@nishtha82 I've improved the error message when the R process errors ; can you try again ? 
  Best,

**Comment by nishtha82** [comment]
@Diviyan-Kalainathan  Hello, I ran the latest!!
It works, this is awesome!
Thanks:)
My output was
```
Detecting 1 CUDA device(s).
C:\Program Files\R\R-4.0.2\bin\Rscript C:\Users\DELL\AppData\Local\Temp\cdt_R_script_28ac4331-5282-4bd2-8cb7-9f9a5741bfbb\instance_test_import.R
C:\Program Files\R\R-4.0.2\bin\Rscript C:\Users\DELL\AppData\Local\Temp\cdt_R_script_793e69d0-aa1c-4f07-acfe-4545efb9fbd5\instance_test_import.R
C:\Program Files\R\R-4.0.2\bin\Rscript C:\Users\DELL\AppData\Local\Temp\cdt_R_script_b2996e20-95c7-47ad-9dad-b0f2b220e9b9\instance_test_import.R
```

and the graph plot when I ran 
```
import cdt
import networkx as nx
from cdt.causality.graph import PC
from cdt.data import load_dataset
import matplotlib.pyplot as plt
data, graph = load_dataset("sachs")
cdt.SETTINGS.rpath = r'C:\Program Files\R\R-4.0.2\bin\Rscript'
obj = PC()
output = obj.predict(data)
nx.draw_networkx(output, font_size=8)
plt.show()
```

**Comment by Diviyan-Kalainathan** [comment]
Hello, 
Great ! I may have left a print somewhere, i'll wait for @Margaux-Chevallier and push to master to release the next version

Best,
Diviyan

**Comment by Margaux-Chevallier** [comment]
It's working for me too !

Thanks !

**Comment by Diviyan-Kalainathan** [comment]
Fantastic, I'll be closing this issue !

**Comment by atulrawal** [comment]
HI,

I'm using google colab and getting an error listed below. 

ImportError: R Package (k)pcalg/RCIT is not available. RCIT has to be installed from https://github.com/Diviyan-Kalainathan/RCIT

I installed RCIT from github in the previous cell using

%%R
install_github("Diviyan-Kalainathan/RCIT")


--Thank You
