### ISSUE TITLE
Errors when using SID in cdt.metrics

### ISSUE THREAD

**Issue by chengweiclarence** [FenTechSolutions/CausalDiscoveryToolbox#78]
Hi!

When running SID by the given example, an error occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-3-9b74660d187b> in <module>
      5 tar = np.triu(randint(2, size=(10, 10)))
      6 pred = np.triu(randint(2, size=(10, 10)))
----> 7 SID(tar, pred)

c:\users\sx-liang\appdata\local\programs\python\python37\lib\site-packages\cdt\metrics.py in SID(target, pred)
    271    """
    272     if not RPackages.SID:
--> 273         raise ImportError("SID R package is not available. Please check your installation.")
    274 
    275     true_labels = retrieve_adjacency_matrix(target)

ImportError: SID R package is not available. Please check your installation.

But when running SHD, everything goes well. Could you tell me how to fix it? Thanks!

**Comment by Diviyan-Kalainathan** [comment]
Hello ! 
Is the R package SID is available in your R installation ? Try: 
```R
install.packages("BiocManager")
BiocManager::install(c("CAM", "SID", "bnlearn", "pcalg", "kpcalg", "D2C"))
```

Best,
Diviyan

**Comment by chengweiclarence** [comment]
> Hello !
> Is the R package SID is available in your R installation ? Try in R:
> 
> ```r
> install.packages("BiocManager")
> BiocManager::install(c("CAM", "SID", "bnlearn", "pcalg", "kpcalg", "D2C"))
> ```
> 
> Best,
> Diviyan


Hi! I have successfully solved this problem by your instruction. Thanks very much!

**Comment by Diviyan-Kalainathan** [comment]
Great, I'll close the issue!
