### ISSUE TITLE
Higher dimension data support

### ISSUE THREAD

**Issue by thongnnguyen** [FenTechSolutions/CausalDiscoveryToolbox#8]
Hi,

I just started to look into your work and really like it.

I started out with the LUCAS example, and wonder if you have any plan to support high dimension features? 

For example: I have a data set where feature 1 is an array of length L but feature 2 is just a single number.

Thanks for the great work, and thanks for using Pytorch.

Cheers,

**Comment by Diviyan-Kalainathan** [comment]
Hi,

Thanks for your interest. Not many algorithms manage this kind of data ;
only one that I know of would be RCC, but I haven't done the adaptation I
think. (I'll do it at the end of the month).
However, it might bring some biased results to perform causal discovery on
data unbalanced in the number of dimensions, as an asymmetry is given by
the dimensions of the data. It's my take on this though, and it would be
interesting to check.

Best,
Diviyan

**Comment by Diviyan-Kalainathan** [comment]
Honestly, I don't think we'll implement this into the CDT any time soon. I will close the issue, but refer to it if I ever adapt all the algorithms to a generic multidimensionnal input.
