### ISSUE TITLE
[BUG] GES + csv file is read wrong in R template

### ISSUE THREAD

**Issue by juangamella** [FenTechSolutions/CausalDiscoveryToolbox#89]
Hi folks,

Looking at the current master branch of the repository, i.e. commit 31809d80098846bafcab08ebb09fd5e0ceb68fba.

In line 26 of the GES R template:

[cdt/causality/graph/R_templates/ges.R](https://github.com/FenTechSolutions/CausalDiscoveryToolbox/blob/master/cdt/causality/graph/R_templates/ges.R)

you do not specify that the csv has no header:

`dataset <- read.csv(file='{FOLDER}{FILE}', sep=",");`

This causes the first row to be lost. The effect is quite subtle. I only noticed because I am reimplementing GES in another language and the likelihood scores between my implementation and that of pcalg did not match. I've spent several days searching for numerical instabilities until I found this. No hard feelings, I'm glad it's over now :)

Best,

Juan

PS: My R version is`3.6.1` and my pcalg version is `2.7.0` although I doubt that matters much.

**Comment by Diviyan-Kalainathan** [comment]
Hello, 
Huge thanks for noticing this ! I'll be fixing this asap!
Out of curiosity, in what language are you reimplementing GES ? 

Best, 
Diviyan

**Comment by juangamella** [comment]
Hi Diviyan,

Thanks for your answer!

In python, so it can also be modified easily by people who don't know R
(like myself).

Glad to be of help :)

Juan

**Comment by Diviyan-Kalainathan** [comment]
This should be fixed, and pushed for the next release :) thanks again !
