### ISSUE TITLE
How to use my data to discover causal relationship? or can it ?

### ISSUE THREAD

**Issue by zjcanjux** [FenTechSolutions/CausalDiscoveryToolbox#94]
How to use my data to discover causal relationship? or can it ?

such as 

I want to discover causal relationship from this data ,
how to use this toolbox?

```
# SIZE = 2000
# x1 = numpy.random.normal(size=SIZE)
# x2 = x1 + numpy.random.normal(size=SIZE)
# x3 = x1 + numpy.random.normal(size=SIZE)
# x4 = x2 + x3/2 + numpy.random.normal(size=SIZE)
# X = pd.DataFrame({'x1' : x1, 'x2' : x2, 'x3' : x3, 'x4' : x4})
```
x1,x2,x3,x4
-0.8453950735788643,-0.8453950735788643,-0.039451770100347,-0.8472361561835472
0.2921829131810577,0.2921829131810577,0.013635202615116027,0.2928192226364298
0.46520841437293176,0.46520841437293176,0.02170972600407015,0.46622153491978835
1.2914334932367038,1.2914334932367038,0.06026689635104617,1.2942459483997526
1.9176191301539114,1.9176191301539114,0.08948889274051587,1.9217952784818022
1.226485018045995,1.226485018045995,0.057235967508813095,1.2291560298630728
1.2776907438047431,1.2776907438047431,0.059625568044221346,1.2804732703134734
1.419648102681549,1.419648102681549,0.06625024479180562,1.4227397807718334
0.795218282577467,0.795218282577467,0.037110186520281786,0.7969500912817468
0.5943135087455528,0.5943135087455528,0.027734630408125793,0.595607791497932
...
```

**Comment by Diviyan-Kalainathan** [comment]
Hello, 
Here´s an example:
```python
from cdt.causality.graph import CAM
from cdt.data import load_dataset
obj = CAM()
output = obj.predict(X)
```
more details here : https://fentechsolutions.github.io/CausalDiscoveryToolbox/html/tutorial_1.html#causal-discovery
